.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. SaruulCoin_qt test_SaruulCoin_qt
clean: FORCE
	$(MAKE) -C .. SaruulCoin_qt_clean test_SaruulCoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_SaruulCoin_qt_check
SaruulCoin-qt SaruulCoin-qt.exe: FORCE
	 $(MAKE) -C .. SaruulCoin_qt
